Домашняя работа №2
JuliaJedi/FocusStartHomeworks pull request #2
Opened 2020-11-08 17:01 UTC by JuliaJedi

Разработано консольное приложение, реализующее работу с потокобезопасным массивом:
1. Создан класс ThreadSafeArray, который может работать с элементами любого типа. Для данного класса реализованы методы append/remove/subscript/contains и определены вычисляемые свойства isEmpty/count
2. В файле main.swift продемонстрирована работа с потокобезопасным Int-овым массивом типа ThreadSafeArray и обычным не потокобезопасным массивом: в concurrent очередь добавлены два задания с заполнением этих двух массивов. При запуске программы видно, что в обычный массив некорректно добавляются значения либо программа вообще падает с ошибками
3. Так же добавлен воркспейс для проектов с домашними заданиями

2020-11-09 17:45 UTC, korshunigor commented
Работа принята на проверку

2020-11-09 17:59 UTC, korshunigor requested changes
Работа очень хорошая, нужно чуть чуть поправить оформление

2020-11-09 17:59 UTC, korshunigor commented on FSHomework2/FSHomework2/ThreadSafeArray.swift
> +	private var isolatedQueue = DispatchQueue(label: "isolatedQueue", attributes: .concurrent)
Можно заменить на let, т.к. дальше по коду мы не изменяем эту очередь

2020-11-09 17:59 UTC, korshunigor commented on FSHomework2/FSHomework2/ThreadSafeArray.swift
> +	var count: Int {
Желательно разделить переносом строки для лучшей читаемости (выше между приватным var и вычислимым свойством тоже)

2020-11-09 17:59 UTC, korshunigor commented on FSHomework2/FSHomework2/main.swift
> +let workerQueue = DispatchQueue(label: "myQueue", attributes: .concurrent)
Это не ошибка, просто на всякий случай отмечаю, т.к. тут мы не пользуемся "плюшками" работы с отдельной очередью (мы ее не блокируем, ни как не управляем выполняющимися задачами и т.д.) можно воспользоваться глобальной очередью предоставляемой из коробки и желательно указав qos, чтобы однозначно определить приоритет выполнения задач, например:
```swift
DispatchQueue.global(qos: .userInitiated)
```

2020-11-10 10:43 UTC, JuliaJedi commented on FSHomework2/FSHomework2/ThreadSafeArray.swift
> +	private var isolatedQueue = DispatchQueue(label: "isolatedQueue", attributes: .concurrent)
Заменила на let

2020-11-10 10:43 UTC, JuliaJedi commented on FSHomework2/FSHomework2/ThreadSafeArray.swift
> +	var count: Int {
Разделила переносом строки

2020-11-10 10:44 UTC, JuliaJedi commented on FSHomework2/FSHomework2/main.swift
> +let workerQueue = DispatchQueue(label: "myQueue", attributes: .concurrent)
Заменила приватную очередь на глобальную

2020-11-11 14:59 UTC, korshunigor approved these changes
Работа принята, можно мержить =)

2020-11-11 16:55 UTC, merged